Global:
  Source: "config(local)"
  ChangeMe: "v1"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "localhost"
  Port: 2379

Server:
  Name: "DouTokCommentServer"
  Address: "127.0.0.1"
  Port: 8089

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"

Otel:
  Host: "82.156.171.8"
  Port: 4317