Global:
  Source: "config(local)"
  ChangeMe: "v1"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

Server:
  Name: "DoutokFavoriteServer"
  Address: "127.0.0.1"
  Port: 8085

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1"