Global:
  Source: "config(local)"
  ChangeMe: "v1"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

Server:
  Name: "DoutokFeedServer"
  Address: "127.0.0.1"
  Port: 8083

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"

MySQL:
  Host: "127.0.0.1"
  Port: 8091
  User: "tiktok"
  Password: "password"
  DBName: "Tiktok"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"