Global:
  Source: "config(local)"
  ChangeMe: "v1"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

Server:
  Name: "DoutokMessageServer"
  Address: "127.0.0.1"
  Port: 8082

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"

Snowflake:
  Node: 10

Hbase:
  Table: "message"

Redis:
  Host: "127.0.0.1"
  Port: 6379
  Password: "root"
  DataBases:
    Default: 5

Kafka:
  Brokers:
    - "150.158.237.39:50004"
  Topics:
    - "test"
  GroupId: "test01"