Global:
  Source: "config(local)"
  ChangeMe: "v1"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

Server:
  Name: "DoutokUserServer"
  Address: "127.0.0.1"
  Port: 8081
  Argon2ID:
    Memory: 64*1024
    Iterations: 3
    Parallelism: 2
    SaltLength: 16
    keyLength: 32

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"